#!/bin/sh

# Installing dependencies for linea
sudo apt install libgtk-3-dev
sudo apt install gcc
sudo apt install g++
sudo apt install libgtk-3-dev
sudo apt install make
sudo apt install libglade2-0 
sudo apt install libglade2-dev
sudo apt install libx11-dev
sudo apt install libxext-dev
sudo apt install libpcap0.8
sudo apt install libcap2
sudo apt install ethtool
#

bash install